name: deepPETase_yml
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8.8
  - numpy=1.19.1
  - pandas=1.1.3
  - tensorflow=2.2.0  
  - scikit-learn=0.23.2
  - biopython=1.79  
  - mmseqs2
  - pip
  - pip:
    - matplotlib
    - xlrd
    - openpyxl
    - ipython